config/routes.rb
Servitoros::Application.routes.draw do
  root :to => 'home#index'

  #devise_for :admin_users, ActiveAdmin::Devise.config
  #ActiveAdmin.routes(self)

  get "home/index"
  get "more_info", :to => "home#more_info"
  get "faq", :to => "home#faq"
  get "credits", :to => "home#credits"

  devise_for :users
  #ActiveAdmin.routes(self)

  resources :executions do
    member { post 'notify' }
    collection do
      post 'notify'
      get 'executions_list'
    end
  end

  resources :uploaded_files, :path => "files", :controller => :files
  resources :files

end

app/views/layouts/_flash_messages.html.erb
<% unless flash.nil? %> 
  <% flash.to_hash.delete_if{|type, message| message.empty?}.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
          <%= render_navigation renderer: :bootstrap %>
        <div class="pull-right">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<%= render :partial => 'shared/header' %>

<div id="page" class="container">
  <%= render partial: "layouts/flash_messages", flash: flash %>
  <div class="row">

    <div class="span12">
      <%= yield %>
    </div>

  </div>
</div>

<%= render :partial => 'shared/footer' %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Servitoros</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<% if params[:action] == "edit" %>
  <%= render :partial => 'layouts/navigation' %>
<% end %>

<div id="page" class="container">
  <%= render partial: "layouts/flash_messages", flash: flash %>
  <div class="row">
      <%= yield %>
  </div>
</div>

</body>
</html>

app/views/layouts/home.html.erb
<% content_for :header_menu do %>
  <%= link_to t(:empieza_usarlo), executions_path, :class => "btn btn-large btn-warning", :id => "engage-btn"  %>
<% end %>

<%= render :partial => 'shared/header' %>

<div class="container main">
  <%= yield %>
</div>


<%= render :partial => 'shared/footer' %>

</body>
</html>